### ISSUE TITLE
Provide an OSX 64 binary release

### ISSUE THREAD

**Issue by stephenlawrence** [rancher/rancher-compose#11]
It would be helpful to have a downloadable binary for various platforms for each release.

**Comment by richburdon** [comment]
Even better, support apt-get and brew for different platforms. I.e., 

> brew install rancher-compose

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

(see "brew install docker-compose").

**Comment by alex88** [comment]
There you go https://github.com/Homebrew/homebrew/pull/43261

**Comment by vincent99** [comment]
Worth pointing out that there is a download link in the UI for Mac/Linux/Windows binaries now, since this is an old issue.
