### ISSUE TITLE
logs command: line break issue

### ISSUE THREAD

**Issue by akurkin** [rancher/rancher-compose#28]
hey guys, looks like there's an issue with `rancher-compose logs` command, as it doesn't respect line breaks (at least for Mac OS X), so all the output just goes into one line.

To reproduce:

- spin up new service using `rancher-compose up`
- run `rancher-compose logs` and see output

**Comment by ibuildthecloud** [comment]
Fixed in https://github.com/rancherio/rancher-compose/pull/30

**Comment by deniseschannon** [comment]
Verified fixed in Linux and Mac OS X with rancher-compose v0.1.3.

@sheng-liang Could you test in Windows?
