### ISSUE TITLE
Warn if key is unknown in debug

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher-compose#32]
Accidentally used volumes-from instead of volumes_from. The command ran, but did not warn about an invalid key. Typically, if you run into an invalid key in a docker-compose file it explodes loudly. I like that Rancher compose keeps going, but it would be nice to know that it encountered something it didn't know about. Debugging would be easier if it warned. 

So, I propose warning while running the command. something like:

[Warn][0000] Found unknown key type `blah` - continuing.

**Comment by ibuildthecloud** [comment]
This is a good idea.  I continually mess this up too.

**Comment by ibuildthecloud** [comment]
This issue is being tracked in libcompose now. https://github.com/docker/libcompose/issues/34
