### ISSUE TITLE
Hangs silently on self link

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher-compose#40]
Create a service that links to itself, and then try to "Up" the service. The command line will just hang. It would be nice if it notified the user of a loop if we aren't going to allow self linking for DNS resolution.

**Comment by ibuildthecloud** [comment]
@cloudnautique Circular links are supported in v0.2.5.  Can you try again?

**Comment by deniseschannon** [comment]
@cloudnautique please open in rancher if this is still an issue, but it should be fixed as of v0.2.5.
