### ISSUE TITLE
rancher-compose needs to exit once complete

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher-compose#45]
Almost all of the time when running rancher-compose, say with 'up', once all tasks are complete the process continues to run - I assume mostly for the end user to monitoring the output from containers.

A kind of non-interactive mode is required for scripts so once all tasks are completed, the process exits 0 (and exits non-zero on failure).

The main use case is for doing CI/CD e.g. Jenkins, Bamboo etc. If this feature is currently supported, please let me know and we look at updating the docs, if not this issue should probably be regarded as a bug (its currently blocking us).

**Comment by flaccid** [comment]
Looks like this is simply a case of using the trailing `-d` option similar to docker-compose?
```
OPTIONS:
   -d	Do not block and log
```
I'll close this out, but wondering if we can make this more obvious in the documentation.

**Comment by deniseschannon** [comment]
I don't believe `-d` doesn't exist in rancher-compose, which is why it's not documented. @ibuildthecloud can help confirm.

**Comment by alena1108** [comment]
@flaccid @deniseschannon  `rancher-compose up -d` will exit when all services are active - confirmed with @ibuildthecloud. It has to be documented though if its not, so adding "doc" label.

**Comment by deniseschannon** [comment]
Thanks @alena1108. I'll update the docs now.
