### ISSUE TITLE
Project/Stack name case sensitivity issue

### ISSUE THREAD

**Issue by adamkdean** [rancher/rancher-compose#53]
Basically, if you have a project name (referred to in the v0.31.0 UI as Stacks) that is for example "Test", and then you provide the rancher-compose CLI with -p Test, it will convert that to lowercase (test) and then be unable to find the stack/project due to test !== Test, so it will try and create test but get back a NotUnique because test and Test are the same when case insensitive.

:sob:

**Comment by deniseschannon** [comment]
This is currently logged in Rancher at https://github.com/rancher/rancher/issues/1684 and the fixes need to happen in Rancher and Rancher-compose are:  https://github.com/rancher/rancher/issues/1693 and  https://github.com/rancher/rancher/issues/1694
