### ISSUE TITLE
rancher-compose update service?

### ISSUE THREAD

**Issue by triptec** [rancher/rancher-compose#61]
Will there be any functionality to update to a new image, say if one uses org/someservice:latest?

**Comment by domderen** [comment]
I am trying to to exactly the same thing using `rancher-compose upgrade` function by creating a `docker-compose.yml` template file, which I later fill with variables describing my new image tag etc. But this is really hard to maintain and error prone.

It would be great if there would be a possibility to just say that service x should update container images to specified version.

**Comment by ibuildthecloud** [comment]
`rancher-compose pull` is in the roadmap.  Also an option to upgrade will be added to additionally pull during upgrade.  I'd expect the work to be done by end of sept (famous last words) if not earlier.

^^ @alena1108 :)

**Comment by ibuildthecloud** [comment]
@domderen.  Docker Compose 1.5 (not released) adds support for environment variable substitution in any value.  So you can do `image: myapp:${VERSION}`.  Will this feature help you?  We will be doing the same in rancher-compose.

**Comment by domderen** [comment]
@ibuildthecloud Yeah is solves part of the problem, but the full solution would come with `rancher-compose pull` I suppose :) That way I would be able to easily update images inside my rancher service whenever a new version is pushed to the docker registry ;)

**Comment by fentas** [comment]
@ibuildthecloud Is there a date in sight for environment variables?

**Comment by ibuildthecloud** [comment]
@fentas The work has started in libcompose, https://github.com/docker/libcompose/pull/47.  I don't think it will take long to get through.

**Comment by deniseschannon** [comment]
`rancher-compose pull` was released in v0.38.1. 

https://github.com/rancher/rancher/releases/tag/v0.38.0
