### ISSUE TITLE
Rancher-compose binary on package managers?

### ISSUE THREAD

**Issue by domderen** [rancher/rancher-compose#65]
Hi,

Is `rancher-compose` binary available to download through any package manager, like `apt-get` or `pip`? Currently to manipulate a rancher service on a CI system, I had to place a binary inside the repository, which is not really convenient. I was wondering if there is a chance to download it from somewhere? 

I know I can just download the latest version from https://releases.rancher.com/compose/beta/latest/rancher-compose-linux-amd64.tar.gz but this archive has a directory inside with the rancher version as part of the name. This makes it hard to use this archive, as with every version update I would have to again reconfigure my CI system to get the binary from the archive. It would cause unexpected failures of the build system.

And finally, downloading that binary straight from the URL instead of package manager, makes it hard to cache such dependency in CI systems such as CircleCI.

Thanks in advance.

**Comment by ibuildthecloud** [comment]
Providing rpm/deb is doable but will take a bit.  If we provided a binary download URL that was not a tgz but just the binary itself would that be better?

**Comment by domderen** [comment]
@ibuildthecloud Yeah that would be perfect ;)

**Comment by domderen** [comment]
@ibuildthecloud or it can be a tgz, just without an additional directory inside the tgz archive ;)

**Comment by ibuildthecloud** [comment]
@domderen For the next release I can do binary and binary.gz/xz

**Comment by VladaPetrovic** [comment]
:+1: that would be great

**Comment by domderen** [comment]
Awesome!

**Comment by robzhu** [comment]
+1 on being able to "apt-get install rancher-compose", but certainly a hosted tar file is also useful.

**Comment by deniseschannon** [comment]
This is now available.

https://storage.googleapis.com/releases.rancher.com/compose/beta/latest/binaries/linux-amd64/rancher-compose
https://storage.googleapis.com/releases.rancher.com/compose/beta/latest/binaries/linux-amd64/rancher-compose.gz
https://storage.googleapis.com/releases.rancher.com/compose/beta/latest/binaries/linux-amd64/rancher-compose.xz
