### ISSUE TITLE
Defining health check within docker-compose

### ISSUE THREAD

**Issue by fentas** [rancher/rancher-compose#66]
Hey there, (ref: rancher/rancher/issues/1916)
is there a way to define "Health Check" within docker-compose.yml
I've only seen it in rancher/ui. Couldn't find it in docker-compose neither.

**Comment by deniseschannon** [comment]
I've just added how to add it into the rancher-compose.yml that can be used with rancher-compose. 

http://docs.rancher.com/rancher/rancher-compose/rancher-services/#health-check-for-services

Also, please note that if you ever see something in the UI and are not sure how to make it into docker-compose.yml and rancher-compose.yml files, you can always click on the stack and click on this logo to get the related files.  From the dropdown of the stack, you can also "export configuration" to download the files. 

![vvvvvvv](https://cloud.githubusercontent.com/assets/11410997/9610140/85624a50-508c-11e5-942f-3da79b8a5bb1.png)
