### ISSUE TITLE
any rancher-compose remote api avaialble?

### ISSUE THREAD

**Issue by ymote** [rancher/rancher-compose#67]
HI,

In my use case, I need to create rancher service with remote API. Now rancher-compose only supports CLI. Is there any rancher compose remote API available?

Yue

**Comment by ibuildthecloud** [comment]
This is in works, but this will be a feature in Rancher and not rancher-compose CLI.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/2008
