### ISSUE TITLE
Error when building image from URL

### ISSUE THREAD

**Issue by Djiit** [rancher/rancher-compose#69]
Hi, 

I don't know if it's related to rancher or rancherOS... Sorry if I'm in the wrong repo.

I tried to use *rancher-compose* with a `build:` instruction set to a HTTP URL (ending with .git).

My only declared host is running *RancherOS* and I got this error when using `rancher-compose up`:

    66a33137-c63a-4931-b839-c7a1ab46ee3e : 404 Client Error: Not Found ("Error trying to use git: exec: "git": executable file not found in $PATH ()")

Did I miss something ? Should I install *git* in RancherOS ?

Thx

**Comment by ibuildthecloud** [comment]
Unfortunately git based builds don't work on Rancher v0.3.x.  This will be addressed in RancherOS v0.4, but we have yet to release v0.4.

**Comment by deniseschannon** [comment]
@Djiit I've closed this issue and moved it to Rancher repository. When v0.4.0 of RancherOS comes out, this should be working.
