### ISSUE TITLE
rancher-compose ps

### ISSUE THREAD

**Issue by fentas** [rancher/rancher-compose#70]
Huhu,
I am wondering. It's not really possible to figure out how many container are currently running with rancher-compose. 
The only 2 possible ways to figure this out (I know of) are rancher/server api or within a managed container per rancher-metadata.
Now it would be nice if 
```bash
$ rancher-compose scale web
```
would return current scale or
```bash
$ rancher-compose scale web=+1 # +/-number
```
would scale service relative to current state.

**Comment by ibuildthecloud** [comment]
How about `rancher-compose ps` on par with the docker compose command?

**Comment by fentas** [comment]
Yeah. Actually this would be really nice and need. :+1:

**Comment by ibuildthecloud** [comment]
Seems reasonable.

**Comment by deniseschannon** [comment]
@fentas we are consolidating the rancher-compose issues into the rancher repo. I've tagged you on the rancher issue to follow.
