### ISSUE TITLE
io.rancher.stack.name

### ISSUE THREAD

**Issue by fentas** [rancher/rancher-compose#73]
HeyHo,
I am wondering. I have a compose file with a few services depending on each other. But I want some in different stacks. I tried labeling them with `io.rancher.stack.name` but seems not to work. Only what `rancher-compose` cli gets seems to have an effect. 
Is it possible to tag services with different stack names within one docker-compose file and run it with single command `rancher-compose up -d`?

**Comment by deniseschannon** [comment]
This is not possible today as it's assumed that all the services are going in the same stack. We can look into it if more users are interested in using labels with stackname to determine the stack.

**Comment by parabuzzle** [comment]
@fentas I have been using `rancher-compose -p <stackname> up` to define the stack with rancher compose.. but then you have to have a docker-compose/rancher-compose file for each stack.. which is probably good practice :)

**Comment by deniseschannon** [comment]
Closed in favor of the rancher issue. Note: I am not tagging the specific issue as whenever we close the issues in Rancher-compose, the rancher-compose links will become 404.
