### ISSUE TITLE
Circular linking between stacks (different docker-compose.yml)

### ISSUE THREAD

**Issue by andrefreitas** [rancher/rancher-compose#90]
If you have a stack for balancers and another for microservices, the stacks have a circular linking. Trying to do rancher-compose create, up or start will raise a Warning that the link failed.

**Comment by deniseschannon** [comment]
What version of rancher-compose are you using? We just released v0.3.0 that fixes the circular link for create and then start. Or if you just do a rancher-compose up should be working as of v0.2.5. The circular linking won't appear in the UI after the create, but the start should fix it (assuming you use the same docker-compose.yml)

**Comment by andrefreitas** [comment]
@deniseschannon It's not a circular link inside the same stack/project/docker-compose-yml, they are from different stacks: balancers and microservices. I already tried up, start and create.

rancher-compose version is v0.2.6

**Comment by deniseschannon** [comment]
Yes, there is probably some bug that we don't wait long enough for links to be established so we timeout. @ibuildthecloud

**Comment by deniseschannon** [comment]
Closing in favor of the rancher issue that was created. @andrefreitas I tagged you in the issue so that you would be following it.
