### ISSUE TITLE
rancher-compose rejects a valid docker-compose file

### ISSUE THREAD

**Issue by miketheman** [rancher/rancher-compose#92]
A [valid docker-compose file](https://github.com/miketheman/dorkbot/blob/master/docker-compose.yml#L9-L10) errors out on rancher-compose over the [`environment` variable setting](https://docs.docker.com/compose/yml/#environment).

```shellsession
$ ./rancher-compose -v
rancher-compose version v0.3.0
$ ./rancher-compose --verbose -f ~/git/miketheman/dorkbot/docker-compose.yml create
DEBU[0000] Opening compose file: /Users/miketheman/git/miketheman/dorkbot/docker-compose.yml
DEBU[0000] Reading file /Users/miketheman/git/miketheman/dorkbot/.env relative to /Users/miketheman/git/miketheman/dorkbot/docker-compose.yml
DEBU[0000] Opening rancher-compose file: /Users/miketheman/git/miketheman/dorkbot/rancher-compose.yml
DEBU[0000] Not found: /Users/miketheman/git/miketheman/dorkbot/rancher-compose.yml
DEBU[0000] Looking for stack dorkbot
INFO[0000] Creating stack dorkbot
ERRO[0000] Failed to open project dorkbot: Resource type [environment] is not creatable
2015/09/20 14:58:55 Failed to read project: Resource type [environment] is not creatable
```

**Comment by ibuildthecloud** [comment]
This happens when you API keys are not valid.  We need to add an error message or check that validates the keys to make this more user friendly.

**Comment by deniseschannon** [comment]
Closed in favor of the rancher issue that was created. Note: This is now an enhancement as it's more indication of API keys were incorrect but we need better error messaging and less confusing terms.
